#!/usr/bin/env python3
from pathlib import Path
from urllib.parse import urlparse
import re
import sys

root = Path(__file__).resolve().parents[2]
public = root / 'site' / 'public'
imports = root / 'imports' / 'esc-int-pages'
baseurl = sys.argv[1] if len(sys.argv) > 1 else '/'
prefix = urlparse(baseurl).path or '/'
if not prefix.startswith('/'):
    prefix = '/' + prefix
if not prefix.endswith('/'):
    prefix += '/'

homepage_path = public / 'index.html'
home = homepage_path.read_text(encoding='utf-8')
main_open = re.search(r'<main\s+id=(?:"main-content"|main-content)>', home)
if not main_open:
    raise SystemExit('ERROR: generated ESC shell main marker missing')
pre = home[:main_open.start()]
rest = home[main_open.end():]
if '</main>' not in rest:
    raise SystemExit('ERROR: generated ESC shell main closing marker missing')
_, post = rest.split('</main>', 1)
open_marker = '<main id="main-content">'

# Canonical sponsor page is generated by Hugo and must never be overwritten by the frozen INT snapshot.
excluded = {'sponsoren'}
count = 0


def rewrite_root_urls(html: str) -> str:
    if prefix == '/':
        return html
    for attr in ('href', 'src'):
        html = html.replace(f'{attr}=/', f'{attr}={prefix}')
        html = html.replace(f'{attr}="/', f'{attr}="{prefix}')
        html = html.replace(f"{attr}='/", f"{attr}='{prefix}")
    return html

for src in sorted(imports.rglob('index.html')):
    rel = src.relative_to(imports)
    parts = rel.parts[:-1]
    if not parts:
        continue
    if parts[0] in excluded:
        continue

    raw = src.read_text(encoding='utf-8')
    match = re.search(r'<main id=main-content>(.*)</main><footer', raw, flags=re.S)
    if not match:
        match = re.search(r'<main id="main-content">(.*)</main><footer', raw, flags=re.S)
    if not match:
        raise SystemExit(f'ERROR: main content not found in {src}')

    imported_main = rewrite_root_urls(match.group(1))
    page = pre + open_marker + imported_main + '</main>' + post

    title = re.search(r'<title>(.*?)</title>', raw, flags=re.S)
    if title:
        page = re.sub(r'<title>.*?</title>', '<title>' + title.group(1) + '</title>', page, count=1, flags=re.S)

    out = public.joinpath(*parts, 'index.html')
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(page, encoding='utf-8')
    count += 1

print(f'Rendered {count} frozen esc-int pages inside esc-digital shell')
